name: Create Release
on: deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'module.zip'
          directory: 'archive'
          exclusions: '*.git /*node_modules/* .editorconfig'
          
